# Generated by Django 5.2 on 2025-05-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_email_alter_customer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
