# Generated by Django 5.2 on 2025-05-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_delete_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sync_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
