# Generated by Django 5.2 on 2025-05-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_sync_enabled'),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_firms', to='customer.customer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='sync.firm')),
            ],
        ),
    ]
