# Generated by Django 5.2 on 2025-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_end_date_alter_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount in percentage (e.g. 10.00 for 10%)', max_digits=5),
        ),
    ]
