# Generated by Django 5.2 on 2025-05-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='currentBalance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='currentBalanceType',
            field=models.TextField(blank=True, null=True),
        ),
    ]
