# Generated by Django 5.2 on 2025-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_party_currentbalance_party_currentbalancetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='owner',
            field=models.TextField(null=True),
        ),
    ]
